### ISSUE TITLE
pitch doesn't appear

### ISSUE THREAD

**Issue by axd1967** [bartromgens/petanque-map-client#2]
https://www.openstreetmap.org/way/717758630 was created a day ago.
maybe the data filters are not complete?
or maybe the data is cahced at petanque map and not refreshed often?

I added a few points around the Ghent area; those don't appear either, so it looks more like a trivial caching issue.

**Comment by axd1967** [comment]
ok now.

**Comment by bartromgens** [comment]
:+1: It only updated every month. I have changed it to daily now.

**Comment by axd1967** [comment]
OK -  and I just stumbled across this: https://github.com/bartromgens/petanque-map-server#cronjob
