### ISSUE TITLE
Is it possible that the map is not updating anymore ?

### ISSUE THREAD

**Issue by Jakkajakka** [bartromgens/petanque-map-client#9]
If yes...what is the frequency of update times for checking if the edit are correct.
http://petanquemap.com/9/5.153927/52.082722/

**Comment by bartromgens** [comment]
It should update every night (CET). I just checked and it seems to update without errors, but please let me know what OSM terrain you expect to be on the map so I can verify.

**Comment by Jakkajakka** [comment]
This one added 25 days ago
http://petanquemap.com/18/3.233731/50.806816/
https://www.openstreetmap.org/way/742007364
And I see now the search for the town/village is gone.

**Comment by bartromgens** [comment]
Thanks for the extra details. The OSM entry looks good. There must be something wrong with the updating. I will look into it as soon as possible.

**Comment by bartromgens** [comment]
@Jakkajakka this is fixed now. Note that http://petanquemap.com/18/3.233731/50.806816/ now shows a terrain item. There was an issue with the update scripts. Sorry for the late reply.
